[project]
name = "clsproperties"
authors = [{name = "Isaac Bell"}]
dynamic = ["version"]
description = "This library provides classproperty objects for controlled access to class attributes."
readme = "README.md"
requires-python = ">=3.6"
license = "MIT"
license-files = ["LICENSE"]
keywords = [
    "python",
    "python3",
    "python-3",
    "lib",
    "library",
    "python-lib",
    "python-library",
    "package",
    "python-package",
    "module",
    "python-module",
    "pypi",
    "pypi-libary",
    "pypi-package",
    "class",
    "classes",
    "metaclass",
    "metaclasses",
    "attribute",
    "attributes",
    "classattribute",
    "classattributes",
    "class-attribute",
    "class-attributes",
    "property",
    "properties",
    "classproperty",
    "classproperties",
    "class-property",
    "class-properties",
    "descriptor",
    "descriptors",
    "getter",
    "getters",
    "getter-function",
    "getter-functions",
    "getter-method",
    "getter-methods",
    "setter",
    "setters",
    "setter-function",
    "setter-functions",
    "setter-method",
    "setter-methods",
    "deleter",
    "deleters",
    "deleter-function",
    "deleter-functions",
    "deleter-method",
    "deleter-methods",
    "getter-setter-deleter",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = []

[project.urls]
Homepage = "https://icb08.github.io/clsproperties/"
Documentation = "https://icb08.github.io/clsproperties/v1.0.0/documentation/"
Repository = "https://github.com/icb08/clsproperties"
ReleaseNotes = "https://github.com/icb08/clsproperties/releases"
Issues = "https://github.com/icb08/clsproperties/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/clsproperties/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = ["/.github"]
